services:
  discord:
    build:
      context: ./discord
    image: discord
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      GCP_PROJECT_ID: bot-discord-493608
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-adc.json
      ENV: developpement
    volumes:
      - /tmp/gcp-adc.json:/tmp/gcp-adc.json:ro
    depends_on:
      gpt:
        condition: service_healthy
      gemini:
        condition: service_healthy
    networks:
      - bot-discord

  gpt:
    build:
      context: ./gpt
    image: gpt
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      GCP_PROJECT_ID: bot-discord-493608
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-adc.json
    volumes:
      - /tmp/gcp-adc.json:/tmp/gcp-adc.json:ro
      - ./data/gpt:/app/data
    ports:
      - "2000:8080"
    networks:
      - bot-discord

  gemini:
    build:
      context: ./gemini
    image: gemini
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      GCP_PROJECT_ID: bot-discord-493608
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-adc.json
    volumes:
      - /tmp/gcp-adc.json:/tmp/gcp-adc.json:ro
    ports:
      - "5000:8080"
    networks:
      - bot-discord

networks:
  bot-discord:
    driver: bridge
